name: Atom Controls Tease
defaultView: viewer
themeDirectory: config/themes/atom_viewer
animateDirectory: config/animations/atom_viewer
controlFile: controls_atom_tease.yml
atomizerId: atom-viewer-tease
classes: [az-overlay-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-atom-viewer-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-atom-viewer]
objects: [nuclets]
canvasRatio: .75
renderer: webgl
startAnimation: true
views:
  viewer:
    name: Atom Viewer
    producer: prod_atom_viewer
    defaultAtom: gold.yml
    defaultTheme: protons
