name: Atom Builder
defaultView: builder
themeDirectory: config/themes/atom_viewer
animateDirectory: config/animations/atom_builder
controlFile: controls_atom_builder.yml
atomizerId: atom-builder
classes: [az-float-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-atom-builder-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-atom-builder]
bindingEnergies: 732
objects: [nuclets]
select: select_atom
canvasRatio: window
renderer: webgl
views:
  builder:
    name: Atom Builder
    producer: prod_atom_builder
    defaultAtom: carbon.yml
#   defaultTheme: electrons-spherical
    defaultTheme: electron-orbitals
