name: Atom Viewer with Nuclets
defaultView: viewer
themeDirectory: config/themes/atom_viewer
animateDirectory: config/animations/atom_viewer
controlFile: controls_atom_viewer_nuclets.yml
atomizerId: atom-viewer
classes: [az-float-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-atom-builder-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-atom-builder]
bindingEnergies: 732
objects: [nuclets]
select: select_atom
canvasRatio: window
renderer: webgl
views:
  viewer:
    name: Atom Viewer w nuclets
    producer: prod_atom_builder
    defaultAtom: carbon.yml
    defaultTheme: protons
