name: Molecule Builder
defaultView: builder
themeDirectory: config/themes/molecule
animateDirectory: config/animations/molecule
controlFile: controls_molecule_builder.yml
atomizerId: molecule-builder
classes: [az-float-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-molecule-builder-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-molecule-builder]
bindingEnergies: 732
objects: [nuclets]
select: select_molecule
canvasRatio: window
renderer: webgl
views:
  builder:
    name: Molecule Builder
    producer: prod_scene
    defaultAtom: carbon.yml
    defaultTheme: electrons-andreas3
