name: None
defaultView: default
themeDirectory: config/themes/atom_viewer
animateDirectory: config/animations/atom_viewer
controlFile: controls_atom_tease.yml
atomizerId: atom-viewer
classes: [az-overlay-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-atom-builder-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-atom-builder]
bindingEnergies: 732
objects: [nuclets]
select: select_atom
canvasRatio: window
renderer: webgl
startAnimation: true
views:
  viewer:
    name: Atom Viewer Tease
    producer: prod_atom_builder
    defaultTheme: protons
