name: Atom Basic
defaultView: viewer
themeDirectory: config/themes/atom_viewer
animateDirectory: config/animations/atom_viewer
controlFile: controls_atom_basic.yml
atomizerId: atom-viewer
classes: [az-overlay-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-atom-viewer-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-atom-viewer]
objects: [nuclets]
canvasRatio: .75
renderer: webgl
views:
  viewer:
    name: Atom Viewer
    producer: prod_atom_viewer
    defaultAtom: carbon.yml
    defaultTheme: protons
