name: Periodic Table Tease
defaultView: default
themeDirectory: config/themes/pte
animateDirectory: config/animations/pte
controlFile: controls_pte_tease.yml
atomizerId: pte-tease
classes: [az-float-controls]
libraries: [atomizer/atomizer-obfuscator, atomizer/atomizer-pte-obfuscator]
librariesDev: [atomizer/atomizer-base, atomizer/atomizer-pte]
objects: [nuclets]
canvasRatio: window
renderer: css3d
views:
  default:
    name: Periodic Table
    producer: prod_pte
    defaultTheme: default
